// jsdom's polyfilled URL mis-resolves `new URL('../../../', import.meta.url)`
// against its synthetic document URL instead of the file: base, so
// fileURLToPath() below throws. This file only touches the filesystem, so
// run it under real Node instead (same remedy as the ERR_REQUIRE_ESM case in
// docs/agent/test-troubleshooting.md).
// @vitest-environment node
// @ts-expect-error node:fs is a Node builtin not typed in browser context
import { existsSync, readFileSync } from 'node:fs'
// @ts-expect-error node:url is a Node builtin not typed in browser context
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { ENV_ICON_FILES } from './icons'
import { oklchToHex } from './oklch'
import { APP_ENVS, type AppEnvName } from './registry'

const clientRoot = fileURLToPath(new URL('../../../', import.meta.url))
const lock = JSON.parse(readFileSync(`${clientRoot}icons.lock.json`, 'utf8')) as Record<
  string,
  { hue: number; hex: string }
>

const branded = (Object.keys(APP_ENVS) as AppEnvName[]).filter(
  (name) => APP_ENVS[name].label !== null,
)

// public/env/** is generated by `pnpm icons:generate` and committed, because
// regeneration needs a Chromium and only matters when the registry changes.
// This test is what makes that safe: change a hue or add an environment
// without regenerating and `pnpm test` fails, naming the stale environment.
describe('icons.lock.json', () => {
  it('covers exactly the branded environments', () => {
    expect(Object.keys(lock).sort()).toEqual([...branded].sort())
  })

  it.each(branded)('matches the registry for %s', (name) => {
    expect(lock[name]).toBeDefined()
    expect(lock[name].hue).toBe(APP_ENVS[name].hue)
    expect(lock[name].hex).toBe(oklchToHex(0.55, 0.17, APP_ENVS[name].hue))
  })

  it.each(branded)('has every committed icon file for %s', (name) => {
    for (const file of ENV_ICON_FILES) {
      expect(existsSync(`${clientRoot}public/env/${name}/${file}`), file).toBe(true)
    }
  })

  it.each(branded)('tints the committed SVGs with the locked accent for %s', (name) => {
    const svg = readFileSync(`${clientRoot}public/env/${name}/favicon.svg`, 'utf8')
    expect(svg).toContain(lock[name].hex)
    expect(svg).not.toContain('#645fd1')
  })
})
