import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const packagesDir = resolve(root, 'packages')
const widgetsDir = resolve(packagesDir, 'widgets')
const portsFile = resolve(widgetsDir, '.ports.json')
const clientCatalogFile = resolve(
  packagesDir,
  'client/src/widget-registry/model/widget-catalog.generated.ts',
)
const clientIconsFile = resolve(
  packagesDir,
  'client/src/widget-registry/model/widget-icons.generated.ts',
)
const serverListFile = resolve(packagesDir, 'server/src/widgets/widget-server-list.generated.ts')
const BANNER = '// AUTO-GENERATED by scripts/codegen.ts. Do not edit.\n\n'

type WidgetClientLike = {
  id: string
  title: string
  description: string
  defaultSize: { w: number; h: number; minW?: number; minH?: number }
  tiers?: unknown
  icon: string
}

export type WidgetMeta = WidgetClientLike & {
  dir: string
}

function ident(dir: string) {
  return dir.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase())
}

function stableJson(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function writeIfChanged(file: string, next: string) {
  mkdirSync(dirname(file), { recursive: true })
  const prev = existsSync(file) ? readFileSync(file, 'utf8') : null
  if (prev === next) return
  writeFileSync(file, next)
}

export function discoverWidgetDirs(dir: string) {
  return readdirSync(dir)
    .filter((name) => !name.startsWith('.'))
    .filter((name) => existsSync(resolve(dir, name, 'package.json')))
    .sort((a, b) => a.localeCompare(b))
}

export function assignPorts(widgetDirs: string[], current: Record<string, number>) {
  const assigned: Record<string, number> = { ...current }
  let nextPort = Math.max(5179, ...Object.values(current)) + 1

  for (const dir of widgetDirs) {
    if (assigned[dir] != null) continue
    assigned[dir] = nextPort
    nextPort += 1
  }

  return assigned
}

export function emitCatalog(metas: WidgetMeta[]) {
  const entries = metas
    .map(
      (meta) => `  toWidgetType({
    id: ${JSON.stringify(meta.id)},
    title: ${JSON.stringify(meta.title)},
    description: ${JSON.stringify(meta.description)},
    defaultSize: ${stableJson(meta.defaultSize).replace(/\n/g, '\n    ')},
    icon: ${JSON.stringify(meta.icon)},${
        meta.tiers
          ? `\n    tiers: ${stableJson(meta.tiers).replace(/\n/g, '\n    ')},`
          : ''
      }
    loadComponent: loadRemoteModule(${JSON.stringify(meta.id)}),
  })`,
    )
    .join(',\n')

  return `${BANNER}import { loadRemote } from '@module-federation/runtime'
import { toWidgetType, type WidgetType } from 'widget-sdk/define-widget-client'
import type { WidgetComponentModule } from 'widget-runtime'

import type { WidgetIconName } from './widget-icons.generated'

function loadRemoteModule(id: string) {
  return async () => {
    const module = await loadRemote<WidgetComponentModule | WidgetComponentModule['default']>(\`\${id}/ui\`)
    if (module && typeof module === 'object' && 'default' in module) {
      return module as WidgetComponentModule
    }
    return { default: module as WidgetComponentModule['default'] }
  }
}

export const widgetTypes = [
${entries}
] as (WidgetType & { icon: WidgetIconName })[]
`
}

export function emitIcons(metas: WidgetMeta[]) {
  const icons = [...new Set(metas.map((meta) => meta.icon))].sort((a, b) => a.localeCompare(b))
  const imports = icons.join(', ')
  const union = icons.map((icon) => `'${icon}'`).join(' | ')
  const map = icons.join(', ')

  return `${BANNER}import type { LucideIcon } from 'lucide-react'
import { ${imports} } from 'lucide-react'

export type WidgetIconName = ${union}

export const WIDGET_ICONS: Record<WidgetIconName, LucideIcon> = { ${map} }
`
}

export function emitServerList(metas: WidgetMeta[]) {
  const imports = metas
    .map((meta) => `import ${ident(meta.dir)} from '@widgets/${meta.dir}/server'`)
    .join('\n')
  const list = metas
    .map((meta) => `  toRuntimeWidgetServerDefinition(${ident(meta.dir)})`)
    .join(',\n')

  return `${BANNER}import { toRuntimeWidgetServerDefinition } from '@shared/widgets/contracts'
${imports}

export const widgetServerList = [
${list}
]
`
}

async function readWidgetMetas(widgetDirs: string[]) {
  const metas: WidgetMeta[] = []

  for (const dir of widgetDirs) {
    const module = (await import(pathToFileURL(resolve(widgetsDir, dir, 'client.ts')).href)) as {
      default: WidgetClientLike
    }
    const definition = module.default
    metas.push({
      dir,
      id: definition.id,
      title: definition.title,
      description: definition.description,
      defaultSize: definition.defaultSize,
      tiers: definition.tiers,
      icon: definition.icon,
    })
  }

  return metas
}

async function main() {
  const widgetDirs = discoverWidgetDirs(widgetsDir)
  const currentPorts = existsSync(portsFile)
    ? (JSON.parse(readFileSync(portsFile, 'utf8')) as Record<string, number>)
    : {}
  const nextPorts = assignPorts(widgetDirs, currentPorts)
  const metas = await readWidgetMetas(widgetDirs)

  writeIfChanged(portsFile, `${stableJson(nextPorts)}\n`)
  writeIfChanged(clientCatalogFile, emitCatalog(metas))
  writeIfChanged(clientIconsFile, emitIcons(metas))
  writeIfChanged(serverListFile, emitServerList(metas))
}

void main().catch((error: unknown) => {
  console.error(error)
  process.exitCode = 1
})
