import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import * as errore from 'errore'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const packagesDir = path.resolve(root, 'packages')

export type CodegenPaths = {
  widgetsDir: string
  portsFile: string
  clientCatalogFile: string
  clientIconsFile: string
  serverListFile: string
}

export type ClientCodegenPaths = Pick<
  CodegenPaths,
  'widgetsDir' | 'portsFile' | 'clientCatalogFile' | 'clientIconsFile'
>
export type ServerCodegenPaths = Pick<CodegenPaths, 'widgetsDir' | 'serverListFile'>
export type CodegenTarget = 'client' | 'server' | 'all'
export type GeneratedOutput = { file: string; content: string }

export const BANNER = '// AUTO-GENERATED by scripts/codegen.ts. Do not edit.\n\n'

export class CodegenIoError extends errore.createTaggedError({
  name: 'CodegenIoError',
  message: 'Failed to $operation codegen path $path',
}) {}
export class MissingWidgetEntrypointError extends errore.createTaggedError({
  name: 'MissingWidgetEntrypointError',
  message: 'Widget $widgetId is missing its $side entrypoint at $path',
}) {}
export class InvalidCodegenTargetError extends errore.createTaggedError({
  name: 'InvalidCodegenTargetError',
  message: 'Unknown codegen target: $target',
}) {}

export function parseCodegenTarget(raw: string): InvalidCodegenTargetError | CodegenTarget {
  if (raw === 'client' || raw === 'server' || raw === 'all') return raw
  return new InvalidCodegenTargetError({ target: raw })
}

export const defaultCodegenPaths: CodegenPaths = {
  widgetsDir: path.resolve(packagesDir, 'widgets'),
  portsFile: path.resolve(packagesDir, 'widgets/.ports.json'),
  clientCatalogFile: path.resolve(
    packagesDir,
    'client/src/widget-registry/model/widget-catalog.generated.ts',
  ),
  clientIconsFile: path.resolve(
    packagesDir,
    'client/src/widget-registry/model/widget-icons.generated.ts',
  ),
  serverListFile: path.resolve(packagesDir, 'server/src/widgets/widget-server-list.generated.ts'),
}

export function discoverWidgetDirs(dir: string): CodegenIoError | string[] {
  const entries = errore.try(() => fs.readdirSync(dir))
  if (entries instanceof Error) {
    return new CodegenIoError({ operation: 'read', path: dir, cause: entries })
  }
  return entries
    .filter((name) => !name.startsWith('.'))
    .filter((name) => fs.existsSync(path.resolve(dir, name, 'package.json')))
    .sort((a, b) => a.localeCompare(b))
}

export function assignPorts(widgetDirs: string[], current: Record<string, number>) {
  const assigned: Record<string, number> = { ...current }
  let nextPort = Math.max(5179, ...Object.values(current)) + 1
  for (const dir of widgetDirs) {
    if (assigned[dir] != null) continue
    assigned[dir] = nextPort++
  }
  return assigned
}

export function writeIfChanged(file: string, next: string): Error | void {
  const previous = fs.existsSync(file) ? errore.try(() => fs.readFileSync(file, 'utf8')) : null
  if (previous instanceof Error) {
    return new CodegenIoError({ operation: 'read', path: file, cause: previous })
  }
  if (previous === next) return
  const directory = path.dirname(file)
  const created = errore.try(() => fs.mkdirSync(directory, { recursive: true }))
  if (created instanceof Error) {
    return new CodegenIoError({ operation: 'create', path: directory, cause: created })
  }
  const written = errore.try(() => fs.writeFileSync(file, next))
  if (written instanceof Error) {
    return new CodegenIoError({ operation: 'write', path: file, cause: written })
  }
}

export function writeGeneratedOutputs(outputs: GeneratedOutput[]): Error | void {
  for (const output of outputs) {
    const result = writeIfChanged(output.file, output.content)
    if (result instanceof Error) return result
  }
}

export function identifierFromDirectory(dir: string) {
  return dir.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase())
}

export function stableJson(value: unknown) {
  return JSON.stringify(value, null, 2)
}
