import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import * as errore from 'errore'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const packagesDir = path.resolve(root, 'packages')

export type CodegenPaths = {
  widgetsDir: string
  portsFile: string
  clientCatalogFile: string
  clientIconsFile: string
  serverListFile: string
}

export type ClientCodegenPaths = Pick<
  CodegenPaths,
  'widgetsDir' | 'portsFile' | 'clientCatalogFile' | 'clientIconsFile'
>
export type ServerCodegenPaths = Pick<CodegenPaths, 'widgetsDir' | 'serverListFile'>
export type CodegenTarget = 'client' | 'server' | 'all'
export type GeneratedOutput = { file: string; content: string }

export const BANNER = '// AUTO-GENERATED by scripts/codegen.ts. Do not edit.\n\n'

export class CodegenIoError extends errore.createTaggedError({
  name: 'CodegenIoError',
  message: 'Failed to $operation codegen path $path',
}) {}
export class MissingWidgetEntrypointError extends errore.createTaggedError({
  name: 'MissingWidgetEntrypointError',
  message: 'Widget $widgetId is missing its $side entrypoint at $path',
}) {}
export class InvalidCodegenTargetError extends errore.createTaggedError({
  name: 'InvalidCodegenTargetError',
  message: 'Unknown codegen target: $target',
}) {}
export class InvalidPortsConfigError extends errore.createTaggedError({
  name: 'InvalidPortsConfigError',
  message: 'Invalid widget ports config at $path',
}) {}
export class PortAllocationError extends errore.createTaggedError({
  name: 'PortAllocationError',
  message: 'No TCP port is available for widget $widgetId',
}) {}

export function parseCodegenTarget(raw: string): InvalidCodegenTargetError | CodegenTarget {
  if (raw === 'client' || raw === 'server' || raw === 'all') return raw
  return new InvalidCodegenTargetError({ target: raw })
}

export const defaultCodegenPaths: CodegenPaths = {
  widgetsDir: path.resolve(packagesDir, 'widgets'),
  portsFile: path.resolve(packagesDir, 'widgets/.ports.json'),
  clientCatalogFile: path.resolve(
    packagesDir,
    'client/src/widget-registry/model/widget-catalog.generated.ts',
  ),
  clientIconsFile: path.resolve(
    packagesDir,
    'client/src/widget-registry/model/widget-icons.generated.ts',
  ),
  serverListFile: path.resolve(packagesDir, 'server/src/widgets/widget-server-list.generated.ts'),
}

export function discoverWidgetDirs(dir: string): CodegenIoError | string[] {
  const entries = errore.try(() => fs.readdirSync(dir))
  if (entries instanceof Error) {
    return new CodegenIoError({ operation: 'read', path: dir, cause: entries })
  }
  return entries
    .filter((name) => !name.startsWith('.'))
    .filter((name) => fs.existsSync(path.resolve(dir, name, 'package.json')))
    .sort((a, b) => a.localeCompare(b))
}

export function assignPorts(widgetDirs: string[], current: Record<string, number>) {
  const assigned: Record<string, number> = { ...current }
  let nextPort = Math.max(5179, ...Object.values(current)) + 1
  for (const dir of widgetDirs) {
    if (assigned[dir] != null) continue
    if (nextPort > 65_535) return new PortAllocationError({ widgetId: dir })
    assigned[dir] = nextPort++
  }
  return assigned
}

export function writeGeneratedOutputs(outputs: GeneratedOutput[]): Error | void {
  const pending: { file: string; temporary: string }[] = []
  for (const [index, output] of outputs.entries()) {
    const previous = fs.existsSync(output.file)
      ? errore.try(() => fs.readFileSync(output.file, 'utf8'))
      : null
    if (previous instanceof Error) {
      cleanupTemporaryFiles(pending)
      return new CodegenIoError({ operation: 'read', path: output.file, cause: previous })
    }
    if (previous === output.content) continue
    const directory = path.dirname(output.file)
    const created = errore.try(() => fs.mkdirSync(directory, { recursive: true }))
    if (created instanceof Error) {
      cleanupTemporaryFiles(pending)
      return new CodegenIoError({ operation: 'create', path: directory, cause: created })
    }
    const temporary = `${output.file}.codegen-${process.pid}-${index}.tmp`
    const written = errore.try(() => fs.writeFileSync(temporary, output.content))
    if (written instanceof Error) {
      cleanupTemporaryFiles(pending)
      return new CodegenIoError({ operation: 'write', path: temporary, cause: written })
    }
    pending.push({ file: output.file, temporary })
  }

  const committed: { file: string; backup: string | null }[] = []
  for (const [index, output] of pending.entries()) {
    const backup = fs.existsSync(output.file)
      ? `${output.file}.codegen-${process.pid}-${index}.bak`
      : null
    const backedUp =
      backup === null ? undefined : errore.try(() => fs.renameSync(output.file, backup))
    if (backedUp instanceof Error) {
      rollbackGeneratedOutputs(committed, pending)
      return new CodegenIoError({ operation: 'backup', path: output.file, cause: backedUp })
    }
    const renamed = errore.try(() => fs.renameSync(output.temporary, output.file))
    if (renamed instanceof Error) {
      const restored =
        backup === null ? undefined : errore.try(() => fs.renameSync(backup, output.file))
      if (restored instanceof Error)
        console.warn('Failed to restore generated output backup', restored)
      rollbackGeneratedOutputs(committed, pending)
      return new CodegenIoError({ operation: 'replace', path: output.file, cause: renamed })
    }
    committed.push({ file: output.file, backup })
  }
  for (const output of committed) {
    if (output.backup === null) continue
    const removed = errore.try(() => fs.rmSync(output.backup, { recursive: true }))
    if (removed instanceof Error) {
      return new CodegenIoError({ operation: 'remove backup', path: output.backup, cause: removed })
    }
  }
}

export function identifierFromDirectory(dir: string) {
  if (isJavaScriptIdentifier(dir) && !dir.startsWith('$')) return dir
  if (/^[a-z][a-z0-9]*(?:-[a-z0-9]+)+$/.test(dir)) {
    const camelCase = dir.replace(/-([a-z0-9])/g, (_, character: string) =>
      character.toUpperCase(),
    )
    if (isJavaScriptIdentifier(camelCase)) return camelCase
  }
  return `$${[...dir].map((character) => character.codePointAt(0)!.toString(16)).join('_')}`
}

export function isJavaScriptIdentifier(value: string) {
  const reserved = new Set([
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'enum',
    'export',
    'extends',
    'false',
    'finally',
    'for',
    'function',
    'if',
    'implements',
    'import',
    'in',
    'instanceof',
    'interface',
    'let',
    'new',
    'null',
    'package',
    'private',
    'protected',
    'public',
    'return',
    'static',
    'super',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
  ])
  return /^[A-Za-z_$][\w$]*$/.test(value) && !reserved.has(value)
}

export function stableJson(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function cleanupTemporaryFiles(outputs: { temporary: string }[]) {
  for (const output of outputs) {
    const removed = errore.try(() => fs.rmSync(output.temporary, { force: true }))
    if (removed instanceof Error) console.warn('Failed to remove codegen temporary file', removed)
  }
}

function rollbackGeneratedOutputs(
  committed: { file: string; backup: string | null }[],
  pending: { temporary: string }[],
) {
  for (const output of [...committed].reverse()) {
    const removed = errore.try(() => fs.rmSync(output.file, { force: true }))
    if (removed instanceof Error)
      console.warn('Failed to remove generated output during rollback', removed)
    if (output.backup === null) continue
    const restored = errore.try(() => fs.renameSync(output.backup!, output.file))
    if (restored instanceof Error)
      console.warn('Failed to restore generated output backup', restored)
  }
  cleanupTemporaryFiles(pending)
}
